# Generated by Django 6.0.3 on 2026-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
        ('blog', '0008_comment'),
    ]

    operations = [
    ]
